server:
  port: 9090

spring:
  application:
    name: msvc-asignaturas
 
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres-db:5432/asignaturasDB 
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    register-with-eureka: true  
    fetch-registry: true
    service-url:
      defaultZone: http://microservicio-eureka:8761/eureka
    healthcheck:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true


